/**
 * OneAquaHealth Catalogue of Measures (Seed & Reference Data)
 * 
 * Provides structured operational measures conforming to Phase 4 PRD Sections 8 and 9.
 * Distinguishes OFFICIAL_OAH_MEASURE from AQUASENTINEL_DERIVED_OPERATIONAL_TASK with full provenance.
 */

import { CatalogueMeasure } from '@aquasentinel/shared';

export const SEED_CATALOGUE_MEASURES: CatalogueMeasure[] = [
  {
    measureId: 'OAH-M-VERIFY-01',
    title: 'Field Rapid Visual & Physical Stream Reach Verification',
    description: 'Dispatch environmental inspector to conduct immediate geotagged photographic survey, assess water odor and surface scums, and verify satellite/sensor indications.',
    measureType: 'FIELD_INVESTIGATION',
    applicableIncidentTypes: [
      'POSSIBLE_CYANOBLOOM',
      'POSSIBLE_EUTROPHICATION',
      'POSSIBLE_SEWAGE_CONTAMINATION',
      'POSSIBLE_INDUSTRIAL_DISCHARGE',
      'UNKNOWN_WATER_QUALITY_ANOMALY',
    ],
    applicableStressors: ['Chlorophyll-a surge', 'Surface cyanobacterial scum', 'Organic pollution', 'Turbidity spike'],
    applicableIndicators: ['NDCI', 'TURBIDITY', 'WATER_COLOR', 'DISSOLVED_OXYGEN'],
    minimumEvidenceBand: 'VERIFY',
    requiredVerification: ['Geotagged photographs', 'In-situ visual odor score', 'Surface water clarity check'],
    spatialRequirements: {
      notes: 'Applicable to all urban and peri-urban stream reaches with public or operator access points.',
    },
    temporalRequirements: {
      maxActionDelayHours: 6,
      seasonality: ['Spring', 'Summer', 'Autumn'],
    },
    implementationComplexity: 'LOW',
    estimatedTimeToInitiate: '2 to 4 hours',
    responsibleStakeholder: 'Municipal Environmental Inspectorate',
    responsibleRole: 'ENVIRONMENTAL_INSPECTOR',
    contraindications: ['Severe weather warning active', 'Extreme flash flood discharge in progress'],
    prerequisites: ['Designated stream access waypoint'],
    sourceReference: 'OneAquaHealth Field Protocol D4.1 — Rapid Urban Stream Health Assessment',
    provenance: {
      sourceName: 'OneAquaHealth Horizon Europe (Grant 101086521)',
      sourceDocument: 'Deliverable D4.1: Citizen & Expert Stream Monitoring Protocols',
      sourceSection: 'Section 3.2: Rapid Visual Verification Protocol',
      catalogueIdentifier: 'OAH-WP4-PROT-01',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'OFFICIAL_OAH_MEASURE',
    },
    humanApprovalRequired: true,
  },
  {
    measureId: 'OAH-M-SAMPLE-02',
    title: 'Targeted Water Grab Sampling for Cyanotoxin & Nutrient Analysis',
    description: 'Collect depth-integrated stream water samples for certified laboratory quantification of microcystins, chlorophyll-a, nitrates, and total phosphorus.',
    measureType: 'FIELD_INVESTIGATION',
    applicableIncidentTypes: [
      'POSSIBLE_CYANOBLOOM',
      'POSSIBLE_EUTROPHICATION',
      'POSSIBLE_SEWAGE_CONTAMINATION',
    ],
    applicableStressors: ['Harmful cyanotoxins', 'Eutrophic nutrient loading', 'Ammonium accumulation'],
    applicableIndicators: ['NDCI', 'TURBIDITY', 'DISSOLVED_OXYGEN', 'PH'],
    minimumEvidenceBand: 'INVESTIGATE',
    requiredVerification: ['Chain of custody documentation', 'Cold-chain sample transit (4°C)', 'Field blank and duplicate sample'],
    spatialRequirements: {
      notes: 'Sample at upstream, mid-reach, and downstream boundary stations.',
    },
    temporalRequirements: {
      maxActionDelayHours: 12,
      seasonality: ['Summer', 'Early Autumn'],
    },
    implementationComplexity: 'MEDIUM',
    estimatedTimeToInitiate: '4 to 8 hours',
    responsibleStakeholder: 'Municipal Water Quality Laboratory',
    responsibleRole: 'WATER_QUALITY_ANALYST',
    contraindications: ['Freezing conditions', 'Unsafe channel banks without harness points'],
    prerequisites: ['Field verification confirming active discolored water body'],
    sourceReference: 'OneAquaHealth Deliverable D2.3: Water Quality Laboratory Testing Standards',
    provenance: {
      sourceName: 'OneAquaHealth Horizon Europe (Grant 101086521)',
      sourceDocument: 'Deliverable D2.3: Standard Operating Procedures for Urban Stream Sampling',
      sourceSection: 'Section 4.5: Cyanotoxin Grab Sampling SOP',
      catalogueIdentifier: 'OAH-WP2-SOP-04',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'OFFICIAL_OAH_MEASURE',
    },
    humanApprovalRequired: true,
  },
  {
    measureId: 'OAH-M-SENSOR-03',
    title: 'In-Situ Multi-Parameter Sensor Telemetry Review & Recalibration',
    description: 'Perform real-time drift analysis, biofouling diagnostic, and calibration check on in-situ optical turbidity and dissolved oxygen probes.',
    measureType: 'MONITORING',
    applicableIncidentTypes: [
      'POSSIBLE_EUTROPHICATION',
      'POSSIBLE_CYANOBLOOM',
      'POSSIBLE_INDUSTRIAL_DISCHARGE',
      'UNKNOWN_WATER_QUALITY_ANOMALY',
    ],
    applicableStressors: ['Probe biofouling', 'Electronic calibration drift', 'Localized hypoxia'],
    applicableIndicators: ['TURBIDITY', 'DISSOLVED_OXYGEN', 'WATER_TEMP', 'PH'],
    minimumEvidenceBand: 'VERIFY',
    requiredVerification: ['Telemetry signal-to-noise ratio check', 'Recent rainfall correlation check'],
    spatialRequirements: {
      notes: 'Reach segments equipped with automated IoT sensor stations.',
    },
    temporalRequirements: {
      maxActionDelayHours: 24,
    },
    implementationComplexity: 'LOW',
    estimatedTimeToInitiate: '1 to 2 hours',
    responsibleStakeholder: 'Municipal IoT & Environmental Telemetry Team',
    responsibleRole: 'MUNICIPAL_OPERATOR',
    contraindications: ['Sensor node offline / power outage'],
    prerequisites: ['Active IoT telemetry connection'],
    sourceReference: 'AquaSentinel Technical Architecture — In-situ Sensor Quality Assurance Protocol',
    provenance: {
      sourceName: 'AquaSentinel Operations',
      sourceDocument: 'AquaSentinel Operational Engineering Manual v1.0',
      sourceSection: 'Chapter 5: Sensor Telemetry Validation',
      catalogueIdentifier: 'AS-OP-SENS-01',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'AQUASENTINEL_DERIVED_OPERATIONAL_TASK',
    },
    humanApprovalRequired: false,
  },
  {
    measureId: 'OAH-M-CITIZEN-04',
    title: 'Targeted Citizen Science Mobile Verification Broadcast',
    description: 'Issue geo-fenced observation requests to registered OneAquaHealth citizen scientists in the stream corridor to submit geotagged photos and odor reports.',
    measureType: 'MONITORING',
    applicableIncidentTypes: [
      'POSSIBLE_CYANOBLOOM',
      'POSSIBLE_EUTROPHICATION',
      'POSSIBLE_STORMWATER_EVENT',
      'UNKNOWN_WATER_QUALITY_ANOMALY',
    ],
    applicableStressors: ['Visual water discoloration', 'Surface debris', 'Odor nuisance'],
    applicableIndicators: ['WATER_COLOR', 'NDCI', 'TURBIDITY'],
    minimumEvidenceBand: 'VERIFY',
    requiredVerification: ['Minimum 2 independent citizen photo submissions within 3 hours'],
    spatialRequirements: {
      urbanOnly: true,
      notes: 'High citizen pedestrian density corridors along urban promenades.',
    },
    temporalRequirements: {
      maxActionDelayHours: 4,
      seasonality: ['Spring', 'Summer', 'Autumn'],
    },
    implementationComplexity: 'LOW',
    estimatedTimeToInitiate: '30 minutes to 1 hour',
    responsibleStakeholder: 'OneAquaHealth Community Outreach Coordination',
    responsibleRole: 'ENVIRONMENTAL_INSPECTOR',
    contraindications: ['Hazardous weather conditions', 'Nighttime hours (19:00 - 07:00)'],
    prerequisites: ['OneAquaHealth mobile notification service active'],
    sourceReference: 'OneAquaHealth Citizen Engagement Framework D5.2',
    provenance: {
      sourceName: 'OneAquaHealth Horizon Europe (Grant 101086521)',
      sourceDocument: 'Deliverable D5.2: Citizen Science Engagement Strategy',
      sourceSection: 'Section 2.4: Targeted Community Intake Protocols',
      catalogueIdentifier: 'OAH-WP5-CIT-02',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'OFFICIAL_OAH_MEASURE',
    },
    humanApprovalRequired: true,
  },
  {
    measureId: 'OAH-M-SOURCE-05',
    title: 'Upstream Stormwater Outfall & Diffuse Inflow Source Tracing',
    description: 'Inspect municipal storm drains, culvert discharges, and upstream commercial outfalls to locate active illicit discharges or acute nutrient inflows.',
    measureType: 'SOURCE_CONTROL',
    applicableIncidentTypes: [
      'POSSIBLE_SEWAGE_CONTAMINATION',
      'POSSIBLE_INDUSTRIAL_DISCHARGE',
      'POSSIBLE_EUTROPHICATION',
    ],
    applicableStressors: ['Point-source wastewater discharge', 'Industrial chemical discharge', 'Illegal sewer cross-connection'],
    applicableIndicators: ['TURBIDITY', 'PH', 'DISSOLVED_OXYGEN'],
    minimumEvidenceBand: 'INVESTIGATE',
    requiredVerification: ['Outfall dye test or conductivity mapping', 'Upstream vs downstream gradient measurement'],
    spatialRequirements: {
      urbanOnly: true,
      notes: 'Urban reach segments with dense stormwater drainage outfalls.',
    },
    temporalRequirements: {
      maxActionDelayHours: 12,
    },
    implementationComplexity: 'MEDIUM',
    estimatedTimeToInitiate: '2 to 6 hours',
    responsibleStakeholder: 'Municipal Drainage & Sewer Authority',
    responsibleRole: 'ENVIRONMENTAL_INSPECTOR',
    contraindications: ['Active intense precipitation causing dangerous surcharge'],
    prerequisites: ['Reach drainage outfall inventory map'],
    sourceReference: 'OneAquaHealth Deliverable D3.1: Urban Stream Pollution Source Identification Guide',
    provenance: {
      sourceName: 'OneAquaHealth Horizon Europe (Grant 101086521)',
      sourceDocument: 'Deliverable D3.1: Urban Point and Diffuse Source Identification Framework',
      sourceSection: 'Section 5.2: Stormwater Outfall Inspection Protocol',
      catalogueIdentifier: 'OAH-WP3-SRC-01',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'OFFICIAL_OAH_MEASURE',
    },
    humanApprovalRequired: true,
  },
  {
    measureId: 'OAH-M-MONITOR-06',
    title: 'High-Frequency Satellite & Reach Baseline Trend Surveillance',
    description: 'Maintain passive automated multi-temporal Sentinel-2 and weather surveillance without physical field intervention.',
    measureType: 'MONITORING',
    applicableIncidentTypes: [
      'POSSIBLE_STORMWATER_EVENT',
      'UNKNOWN_WATER_QUALITY_ANOMALY',
      'POSSIBLE_EUTROPHICATION',
    ],
    applicableStressors: ['Natural storm sediment runoff', 'Seasonal temperature stratification'],
    applicableIndicators: ['NDCI', 'TURBIDITY', 'WATER_TEMP'],
    minimumEvidenceBand: 'NORMAL',
    requiredVerification: ['Next Sentinel-2 acquisition within 5 days'],
    spatialRequirements: {
      notes: 'All reaches.',
    },
    temporalRequirements: {
      maxActionDelayHours: 72,
    },
    implementationComplexity: 'LOW',
    estimatedTimeToInitiate: 'Immediate (automated)',
    responsibleStakeholder: 'AquaSentinel Automated Intelligence Engine',
    responsibleRole: 'WATER_QUALITY_ANALYST',
    contraindications: [],
    prerequisites: ['Active Copernicus Open Access Hub connection'],
    sourceReference: 'AquaSentinel Technical Architecture — Continuous EO Monitoring Protocol',
    provenance: {
      sourceName: 'AquaSentinel Operations',
      sourceDocument: 'AquaSentinel Operational Engineering Manual v1.0',
      sourceSection: 'Chapter 2: Automated Reach Monitoring',
      catalogueIdentifier: 'AS-OP-MON-01',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'AQUASENTINEL_DERIVED_OPERATIONAL_TASK',
    },
    humanApprovalRequired: false,
  },
  {
    measureId: 'OAH-M-ADVISORY-07',
    title: 'Draft Precautionary Recreational Water Contact Advisory',
    description: 'Prepare a draft municipal advisory warning citizens against swimming, pet watering, and recreational contact in affected reach pending laboratory confirmation.',
    measureType: 'PUBLIC_ADVISORY',
    applicableIncidentTypes: [
      'POSSIBLE_CYANOBLOOM',
      'POSSIBLE_SEWAGE_CONTAMINATION',
    ],
    applicableStressors: ['Potential cyanobacterial hepatotoxins', 'Pathogenic bacterial contamination'],
    applicableIndicators: ['NDCI', 'WATER_COLOR'],
    minimumEvidenceBand: 'PRIORITIZE',
    requiredVerification: ['Laboratory sample confirmation or multi-source corroboration with photo verification'],
    spatialRequirements: {
      urbanOnly: true,
      notes: 'Recreational water reaches and urban parks.',
    },
    temporalRequirements: {
      maxActionDelayHours: 4,
    },
    implementationComplexity: 'HIGH',
    estimatedTimeToInitiate: '1 to 2 hours',
    responsibleStakeholder: 'Municipal Public Health Directorate',
    responsibleRole: 'PUBLIC_HEALTH_OFFICER',
    contraindications: ['Normal baseline water conditions', 'Isolated uncorroborated satellite pixel'],
    prerequisites: ['Prioritized evidence assessment (Score >= 80) and Human Officer review'],
    sourceReference: 'OneAquaHealth Horizon Europe Guidelines for Urban Water Risk Communication D4.3',
    provenance: {
      sourceName: 'OneAquaHealth Horizon Europe (Grant 101086521)',
      sourceDocument: 'Deliverable D4.3: Health Risk Communication & Early Warning Procedures',
      sourceSection: 'Section 4.1: Precautionary Recreational Advisory Guidelines',
      catalogueIdentifier: 'OAH-WP4-ADV-01',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'OFFICIAL_OAH_MEASURE',
    },
    humanApprovalRequired: true,
  },
  {
    measureId: 'OAH-M-NBS-08',
    title: 'Riparian Buffer Strip & Biofilter Silt Trap Rapid Deployment',
    description: 'Evaluate candidate reach for rapid placement of temporary coir logs, sediment traps, or vegetated buffer enhancement to intercept diffuse agricultural or urban runoff.',
    measureType: 'NATURE_BASED_SOLUTION',
    applicableIncidentTypes: [
      'POSSIBLE_EUTROPHICATION',
      'POSSIBLE_STORMWATER_EVENT',
    ],
    applicableStressors: ['Diffuse agricultural phosphorus', 'Urban road runoff siltation', 'Bank erosion'],
    applicableIndicators: ['TURBIDITY', 'NDCI'],
    minimumEvidenceBand: 'INVESTIGATE',
    requiredVerification: ['Riparian slope assessment', 'Stream reach bank accessibility survey'],
    spatialRequirements: {
      minReachWidthMeters: 5,
      notes: 'Stream banks with gentle to moderate grade.',
    },
    temporalRequirements: {
      maxActionDelayHours: 48,
      seasonality: ['Spring', 'Autumn'],
    },
    implementationComplexity: 'MEDIUM',
    estimatedTimeToInitiate: '24 to 48 hours',
    responsibleStakeholder: 'River Basin Management & Nature Restoration Department',
    responsibleRole: 'RIVER_BASIN_MANAGER',
    contraindications: ['Concrete channelized canals', 'Active flood emergency'],
    prerequisites: ['Landowner consent / municipal riparian easement'],
    sourceReference: 'OneAquaHealth Horizon Europe D3.2 — Nature-Based Solutions Catalogue',
    provenance: {
      sourceName: 'OneAquaHealth Horizon Europe (Grant 101086521)',
      sourceDocument: 'Deliverable D3.2: Catalogue of Nature-Based Measures for Urban Stream Health',
      sourceSection: 'Measure NBS-08: Riparian Vegetative Buffer Enhancement',
      catalogueIdentifier: 'OAH-WP3-NBS-08',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'OFFICIAL_OAH_MEASURE',
    },
    humanApprovalRequired: true,
  },
  {
    measureId: 'OAH-M-REMED-09',
    title: 'Upstream Retention Basin Flushing & Diversion Plan Preparation',
    description: 'Prepare an operational plan to regulate upstream retention gate orifices or divert acute polluted pulse into emergency holding basins.',
    measureType: 'OPERATIONAL_DISPATCH',
    applicableIncidentTypes: [
      'POSSIBLE_SEWAGE_CONTAMINATION',
      'POSSIBLE_INDUSTRIAL_DISCHARGE',
      'POSSIBLE_STORMWATER_EVENT',
    ],
    applicableStressors: ['Combined sewer overflow plume', 'Acute chemical discharge slug'],
    applicableIndicators: ['TURBIDITY', 'PH'],
    minimumEvidenceBand: 'PRIORITIZE',
    requiredVerification: ['Sensor confirmation at downstream control weir', 'Basin storage capacity check'],
    spatialRequirements: {
      notes: 'Reaches downstream of controlled retention or diversion structures.',
    },
    temporalRequirements: {
      maxActionDelayHours: 4,
    },
    implementationComplexity: 'HIGH',
    estimatedTimeToInitiate: '2 to 4 hours',
    responsibleStakeholder: 'Municipal Water Infrastructure Operations',
    responsibleRole: 'MUNICIPAL_OPERATOR',
    contraindications: ['Retention basin at 100% capacity', 'Flash flood warning in catchment'],
    prerequisites: ['Verified upstream spill or overflow event'],
    sourceReference: 'OneAquaHealth Technical Protocol D3.3: Urban Stream Hydraulic Management',
    provenance: {
      sourceName: 'OneAquaHealth Horizon Europe (Grant 101086521)',
      sourceDocument: 'Deliverable D3.3: Water Infrastructure Control & Hydraulic Intervention Protocols',
      sourceSection: 'Section 6.3: Emergency Basin Diversion Procedures',
      catalogueIdentifier: 'OAH-WP3-HYD-03',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'OFFICIAL_OAH_MEASURE',
    },
    humanApprovalRequired: true,
  },
  {
    measureId: 'OAH-M-ESCALATE-10',
    title: 'Regional Environmental Protection Agency Formal Incident Escalation',
    description: 'Compile verified evidence package and formally transmit notification to Regional Environmental Protection Agency and River Basin District Authority.',
    measureType: 'OPERATIONAL_DISPATCH',
    applicableIncidentTypes: [
      'POSSIBLE_CYANOBLOOM',
      'POSSIBLE_INDUSTRIAL_DISCHARGE',
      'POSSIBLE_SEWAGE_CONTAMINATION',
      'POSSIBLE_EUTROPHICATION',
    ],
    applicableStressors: ['Cross-jurisdictional water hazard', 'Severe water directive non-compliance'],
    applicableIndicators: ['NDCI', 'TURBIDITY', 'DISSOLVED_OXYGEN'],
    minimumEvidenceBand: 'PRIORITIZE',
    requiredVerification: ['Completed evidence assessment with score >= 80 and officer signature'],
    spatialRequirements: {
      notes: 'All reaches with regional or cross-boundary significance.',
    },
    temporalRequirements: {
      maxActionDelayHours: 2,
    },
    implementationComplexity: 'MEDIUM',
    estimatedTimeToInitiate: '1 hour',
    responsibleStakeholder: 'Municipal Environmental Compliance Office',
    responsibleRole: 'RIVER_BASIN_MANAGER',
    contraindications: ['Uncorroborated single sensor glitch', 'EvidenceBand < PRIORITIZE'],
    prerequisites: ['Approved Incident Recommendation Record'],
    sourceReference: 'European Water Framework Directive (2000/60/EC) Article 14 Escalation Framework',
    provenance: {
      sourceName: 'OneAquaHealth Regulatory Alignment Report',
      sourceDocument: 'Deliverable D1.4: Compliance with European Water Framework Directives',
      sourceSection: 'Section 5.1: Cross-Agency Reporting Standards',
      catalogueIdentifier: 'OAH-WP1-REG-01',
      ingestionDate: '2026-09-01T00:00:00.000Z',
      version: '1.0.0',
      provenanceStatus: 'OFFICIAL_OAH_MEASURE',
    },
    humanApprovalRequired: true,
  },
];
